#
# This file is part of the cry package
#

#########
### Functions for calculations related to the crystal lattice
#########


#' Calculation of useful lattice parameters
#'
#' @param a A real number. One of the unit cell's side lengths, in angstroms.
#' @param b A real number. One of the unit cell's side lengths, in angstroms.
#' @param c A real number. One of the unit cell's side lengths, in angstroms.
#' @param aa A real number. One of the unit cell's angles, in degrees.
#' @param bb A real number. One of the unit cell's angles, in degrees.
#' @param cc A real number. One of the unit cell's angles, in degrees.
#' @return A named vector of real numbers and length 16. The names are:
#'  \itemize{
#'   \item{sa.   Sine(aa)}
#'   \item{sb.   Sine(bb)}
#'   \item{sc.   Sine(cc)}
#'   \item{ca.   Cosine(aa)}
#'   \item{cb.   Cosine(bb)}
#'   \item{cc.   Cosine(cc)}
#'   \item{ar.   a* (reciprocal cell side length)}
#'   \item{br.   b* (reciprocal cell side length)}
#'   \item{cr.   c* (reciprocal cell side length)}
#'   \item{sar.  Sine of a reciprocal cell angle}
#'   \item{sbr.  Sine of a reciprocal cell angle}
#'   \item{scr.  Sine of a reciprocal cell angle}
#'   \item{car.  Cosine of a reciprocal cell angle}
#'   \item{cbr.  Cosine of a reciprocal cell angle}
#'   \item{ccr.  Cosine of a reciprocal cell angle}
#'   \item{V.    Volume of the unit cell in cubic angstroms}
#'  }
#' @examples
#' datadir <- system.file("extdata",package="cry")
#' fname <- file.path(datadir,"insulin_merged.mtz")
#' hdr <- readMTZHeader(fname,messages=FALSE)
#' ucell <- hdr$CELL
#' vtmp <- lattice_stuff(ucell[1],ucell[2],ucell[3],ucell[4],ucell[5],ucell[6])
#' vtmp[1:3]
#' vtmp[4:6]
#' vtmp[7:9]
#' vtmp[10:12]
#' vtmp[13:15]
#' vtmp[16]
#' @export
lattice_stuff <- function(a,b,c,aa,bb,cc)
{
  # Save cc in another variable, as this is used later
  gg <- cc

  aa <- aa*pi/180
  bb <- bb*pi/180
  gg <- gg*pi/180
  sa <- sin(aa)
  sb <- sin(bb)
  sc <- sin(gg)
  ca <- cos(aa)
  cb <- cos(bb)
  cc <- cos(gg)

  # To avoid NaN generated by rounding off errors, use for cell-derived quantities formulas
  # derived previously by computationa crystallographers
  sang <- 0.5*(aa+bb+gg)
  V2 <- sqrt(sin(sang-aa)*sin(sang-bb)*sin(sang-gg)*sin(sang))
  V <- 2*a*b*c*V2
  ar <- b*c*sa/V
  br <- a*c*sb/V
  cr <- a*b*sc/V
  car <- (cb*cc-ca)/(sb*sc)
  cbr <- (ca*cc-cb)/(sa*sc)
  ccr <- (ca*cb-cc)/(sa*sb)
  sar <- sqrt(1-car*car)
  sbr <- sqrt(1-cbr*cbr)
  scr <- sqrt(1-ccr*ccr)
  ll <- c(sa,sb,sc,ca,cb,cc,ar,br,cr,sar,sbr,scr,car,cbr,ccr,V)
  names(ll) <- c("SIN_ALPHA","SIN_BETA","SIN_GAMMA",
                 "COS_ALPHA","COS_BETA","COS_GAMMA",
                 "A*","B*","C*",
                 "SIN_ALPHA*","SIN_BETA*","SIN_GAMMA*",
                 "COS_ALPHA*","COS_BETA*","COS_GAMMA*","V")

  return(ll)
}


#' Calculates resolution, given the Miller indices
#'
#' @param h An integer, A Miller index.
#' @param k An integer, A Miller index.
#' @param l An integer, A Miller index.
#' @param a A real number. One of the unit cell's side lengths, in angstroms.
#' @param b A real number. One of the unit cell's side lengths, in angstroms.
#' @param c A real number. One of the unit cell's side lengths, in angstroms.
#' @param aa A real number. One of the unit cell's angles, in degrees.
#' @param bb A real number. One of the unit cell's angles, in degrees.
#' @param cc A real number. One of the unit cell's angles, in degrees.
#' @return A positive, real number. The resolution associated with (h,k,l), in angstroms.
#' @examples
#' datadir <- system.file("extdata",package="cry")
#' fname <- file.path(datadir,"insulin_merged.mtz")
#' hdr <- readMTZHeader(fname,messages=FALSE)
#' ucell <- hdr$CELL
#' reso1 <- hkl_to_reso(1,0,0,ucell[1],ucell[2],ucell[3],ucell[4],ucell[5],ucell[6])
#' print(reso1)  # Low resolution
#' reso2 <- hkl_to_reso(20,20,20,ucell[1],ucell[2],ucell[3],ucell[4],ucell[5],ucell[6])
#' reso2  # High resolution
#' @export
hkl_to_reso <- function(h,k,l,a,b,c,aa,bb,cc)
{
  aa <- aa*pi/180
  bb <- bb*pi/180
  cc <- cc*pi/180
  top <- 1-(cos(aa))^2-(cos(bb))^2-(cos(cc))^2+2*cos(aa)*cos(bb)*cos(cc)
  b1 <- h^2*(sin(aa))^2/a^2
  b2 <- k^2*(sin(bb))^2/b^2
  b3 <- l^2*(sin(cc))^2/c^2
  b4 <- 2*h*k*(cos(aa)*cos(bb)-cos(cc))/(a*b)
  b5 <- 2*h*l*(cos(aa)*cos(cc)-cos(bb))/(a*c)
  b6 <- 2*k*l*(cos(bb)*cos(cc)-cos(aa))/(b*c)
  d2 <- top/(b1+b2+b3+b4+b5+b6)
  return(sqrt(d2))
}
